### ISSUE TITLE
cppcheck includePaths?

### ISSUE THREAD

**Issue by cvaliere** [QiuminGe/cpp-checker#41]
How to include paths in cppcheck?
(as described [here](https://cppcheck.sourceforge.io/manual.html#include-paths))

**Comment by QiuminGe** [comment]
Cpp-check-lint › Cppcheck: -i
Give a source file or source file directory to exclude
from the check. This applies only to source files so
header files included by source files are not matched.
Directory name is matched to all parts of the path.
auto add base path

--- try  v1.5.0

**Comment by QiuminGe** [comment]
Cpp-check-lint › Cppcheck: -I
Give paths to search for include files
auto add base path

v1.5.0
